version: "3.9"

services:
  web:
    env_file:
      - .env.docker
    build: .
    ports:
      - "8000:5000"
    volumes:
      - /home/denis/someshit:/code/someshit

  redis:
    image: "redis:alpine"
