name: rebuild web.

on:
  push:

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .

      - name: cp 
        run: cp /tmp/testweb_env/.env.docker .

      - name: cat
        run: cat .env.docker

      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

      - name: Checking if previous container is up
        env:
          PREVIOUS_CONTAINER: false
        run: docker ps #-f "name=ci-cd-testing_web_1" --format {{.Names}}|sed 's/ci-cd-testing_web_1/true/' >> $PREVIOUS_CONTAINER

      - name: Stopping and removing previous container
        if: ${{env.PREVIOUS_CONTAINER == true}}
        run: docker container stop eatlas3

