name: rebuild web.

on:
  workflow_dispatch:
  
jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .
        
      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

      - name: cd
        run: cd /home/dgolod/
      
      - name: ls
        run: ls

