name: rebuild web.

on:
  push:

on:
  workflow_dispatch

env:
  CURRENT_ENV: ${{ secrets.CURRENT_ENV }}

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .
      
      - name: touch
        run: touch .env.docker
      
      - name: pwd
        run: pwd

      - name: ls
        run: ls -la /home/dgolod

      - name: nyum
        run: echo $CURRENT_ENV > .env.docker

      - name: cat
        run: cat .env.docker

      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

