name: rebuild web.

on:
  workflow_dispatch:

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .

      - name: cp 
        run: cp ../_env/.env.docker .

      - name: cat
        run: cat .env.docker

      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

      - name: Checking if previous container is up
        run: docker ps -f "name=ci-cd-testing_web_1" --format {{.Names}}|sed 's/ci-cd-testing_web_1/prev_up=true/' >> $GITHUB_ENV

      - name: echo
        run : if "${{env.prev_up}}" == "true"; then echo WOOHOO; else echo WOW; fi



