name: rebuild web.

on:
  push:

env:
  PREVIOUS_CONTAINER: null

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .

      - name: cp 
        run: cp /tmp/testweb_env/.env.docker .

      - name: cat
        run: cat .env.docker

      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

      - name: Checking if previous container is up
        run: docker ps --format '{{.Names}}' --filter "name=eatlas3" >> $previous_container

      - name: Stopping and removing previous container
        if: $PREVIOUS_CONTAINER == eatlas3
        run: docker container stop eatlas3

