name: rebuild web.

on:
  push:

env:
  PREVIOUS_CONTAINER: false

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .

      - name: rebuild & deploy
        run: docker-compose up -d --build web 

      - name: clear dangling
        run: docker rmi -f $(docker images -f "dangling=true" -q)

      - name: Checking if previous container is up
        run: docker ps -f "name=eatlas3" --format {{.Names}}|sed 's/eatlas3/true/' >> $PREVIOUS_CONTAINER

      - name: Stopping and removing previous container
        if: ${{env.PREVIOUS_CONTAINER == true}}
        run: docker container stop eatlas3

