name: Test git

on:
  workflow_dispatch:

jobs: 
  build:
    name: image build
    runs-on: self-hosted
    steps:
      - name: checking for actual
        uses: actions/checkout@v2.4.2
        with:
          path: .

      - name: branch
        run: git branch
      
      - name: remote
        run: git remote
        
      - name: update file and push to remote
        run: |
          echo "Test push commit to the remote in the workflow" >> test.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update test.txt"
          git push
